### ISSUE TITLE
KeyError: 'title_unique'

### ISSUE THREAD

**Issue by svpn** [skyride/reddit-rss-bot#1]
Followed your usage instructions and I get this :

(reddit-rss-bot) root@nyc:/home/ubuntu/reddit-rss-bot/reddit-rss-bot# python checknews.py
Version 5.2.0 of praw is outdated. Version 5.3.0 was released Sunday December 17, 2017.
Traceback (most recent call last):
  File "checknews.py", line 38, in <module>
    if feed['entries'][0]['title_unique'] != history[name]:
  File "/home/ubuntu/reddit-rss-bot/local/lib/python2.7/site-packages/feedparser.py", line 356, in __getitem__
    return dict.__getitem__(self, key)
KeyError: 'title_unique'

**Comment by kabutor** [comment]
just rename to 'title'
